export enum Constants{
    FETCH_LIST_OF_COUNTRIES = 'FETCH_LIST_OF_COUNTRIES',
    FETCH_LIST_OF_COUNTRIES_SUCCEED = 'FETCH_LIST_OF_COUNTRIES_SUCCEED',
    FETCH_LIST_OF_COUNTRIES_FAILED = 'FETCH_LIST_OF_COUNTRIES_FAILED',
}
